---
- name: Deploy app to ECS
  hosts: local
  gather_facts: false
  collections:
    - community.aws          # use community.* modules for Ansible 2.15
    - amazon.aws             # still fine to keep on the path

  vars:
    aws_region: ap-southeast-2
    cluster_name: myapp-cluster
    service_name: myapp-web-svc
    taskdef_family: myapp-web

  tasks:
    - name: Register new ECS task definition revision
      community.aws.ecs_taskdefinition:
        family: "{{ taskdef_family }}"
        state: present
        launch_type: FARGATE
        network_mode: awsvpc
        cpu: "256"
        memory: "512"
        execution_role_arn: "arn:aws:iam::{{ lookup('aws_account_attribute','account_id') }}:role/ecsTaskExecutionRole"
        task_role_arn: "arn:aws:iam::{{ lookup('aws_account_attribute','account_id') }}:role/myappTaskRole"
        container_definitions:
          - name: myapp-web
            image: "{{ image_uri }}"
            essential: true
            portMappings:
              - containerPort: 80          # change to 8080 if your app listens on 8080
                hostPort: 80               # keep in sync with your service/ALB target port
                protocol: tcp
            logConfiguration:
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/myapp-web"
                awslogs-region: "{{ aws_region }}"
                awslogs-stream-prefix: "ecs"
      register: td

    # The return structure differs across collection versions; normalize it.
    - name: Derive new task definition ARN
      set_fact:
        new_td_arn: >-
          {{ td.taskdefinition.taskDefinition.taskDefinitionArn
             | default(td.task_definition.task_definition_arn)
             | default(td.taskdefinition.task_definition_arn) }}

    - name: Update ECS service to use new task definition
      community.aws.ecs_service:
        state: present
        name: "{{ service_name }}"
        cluster: "{{ cluster_name }}"
        task_definition: "{{ new_td_arn }}"
        desired_count: 1
        force_new_deployment: true
