---
- name: Deploy app to ECS
  hosts: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /opt/ansible/bin/python3
    aws_region: ap-southeast-2
    cluster_name: myapp-cluster
    service_name: myapp-web-svc
    taskdef_family: myapp-web

  collections:
    - community.aws
    - amazon.aws

  tasks:
    - name: Register new ECS task definition revision
      community.aws.ecs_taskdefinition:
        family: "{{ taskdef_family }}"
        state: present
        launch_type: FARGATE
        network_mode: awsvpc
        cpu: "256"
        memory: "512"
        execution_role_arn: "arn:aws:iam::988360983746:role/ecsTaskExecutionRole"
        task_role_arn: "arn:aws:iam::988360983746:role/myappTaskRole"
        containers:
          - name: myapp-web
            image: "{{ image_uri }}"
            essential: true
            portMappings:
              - containerPort: 80
                protocol: tcp
            logConfiguration:
              logDriver: awslogs
              options:
                awslogs-group: "/ecs/myapp-web"
                awslogs-region: "{{ aws_region }}"
                awslogs-stream-prefix: "ecs"
      register: td

    - name: Derive new task definition ARN
      set_fact:
        new_taskdef_arn: >-
          {{
            td.task_definition_arn
              | default(td.taskdefinition.taskDefinitionArn
              | default(td.taskdefinition.taskDefinition.taskDefinitionArn))
          }}

    - name: Update ECS service to use new task definition
      community.aws.ecs_service:
        state: present
        name: "{{ service_name }}"
        cluster: "{{ cluster_name }}"
        task_definition: "{{ new_taskdef_arn }}"
        desired_count: 1
        force_new_deployment: true
        launch_type: FARGATE
        subnets:
          - subnet-03876e719b21eef27
          - subnet-01f2a400dc6fbb9ec
          - subnet-026bb3d764049a583
        security_groups:
          - sg-0e3dcccbda1881c13
        assign_public_ip: true
